import type {Config} from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['"JetBrains Mono"', 'sans-serif'],
        headline: ['"JetBrains Mono"', 'sans-serif'],
        code: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        // Complete Catppuccin color palettes for all themes
        catppuccin: {
          latte: {
            rosewater: '#dc8a78',
            flamingo: '#dd7878',
            pink: '#ea76cb',
            mauve: '#8839ef',
            red: '#d20f39',
            maroon: '#e64553',
            peach: '#fe640b',
            yellow: '#df8e1d',
            green: '#40a02b',
            teal: '#179299',
            sky: '#04a5e5',
            sapphire: '#209fb5',
            blue: '#1e66f5',
            lavender: '#7287fd',
            text: '#4c4f69',
            subtext1: '#5c5f77',
            subtext0: '#6c6f85',
            overlay2: '#7c7f93',
            overlay1: '#8c8fa1',
            overlay0: '#9ca0b0',
            surface2: '#acb0be',
            surface1: '#bcc0cc',
            surface0: '#ccd0da',
            base: '#eff1f5',
            mantle: '#e6e9ef',
            crust: '#dce0e8'
          },
          frappe: {
            rosewater: '#f2d5cf',
            flamingo: '#eebebe',
            pink: '#f4b8e4',
            mauve: '#ca9ee6',
            red: '#e78284',
            maroon: '#ea999c',
            peach: '#ef9f76',
            yellow: '#e5c890',
            green: '#a6d189',
            teal: '#81c8be',
            sky: '#99d1db',
            sapphire: '#85c1dc',
            blue: '#8caaee',
            lavender: '#babbf1',
            text: '#c6d0f5',
            subtext1: '#b5bfe2',
            subtext0: '#a5adce',
            overlay2: '#949cbb',
            overlay1: '#838ba7',
            overlay0: '#737994',
            surface2: '#626880',
            surface1: '#51576d',
            surface0: '#414559',
            base: '#303446',
            mantle: '#292c3c',
            crust: '#232634'
          },
          macchiato: {
            rosewater: '#f4dbd6',
            flamingo: '#f0c6c6',
            pink: '#f5bde6',
            mauve: '#c6a0f6',
            red: '#ed8796',
            maroon: '#ee99a0',
            peach: '#f5a97f',
            yellow: '#eed49f',
            green: '#a6da95',
            teal: '#8bd5ca',
            sky: '#91d7e3',
            sapphire: '#7dc4e4',
            blue: '#8aadf4',
            lavender: '#b7bdf8',
            text: '#cad3f5',
            subtext1: '#b8c0e0',
            subtext0: '#a5adcb',
            overlay2: '#939ab7',
            overlay1: '#8087a2',
            overlay0: '#6e738d',
            surface2: '#5b6078',
            surface1: '#494d64',
            surface0: '#363a4f',
            base: '#24273a',
            mantle: '#1e2030',
            crust: '#181926'
          },
          mocha: {
            rosewater: '#f5e0dc',
            flamingo: '#f2cdcd', 
            pink: '#f5c2e7',
            mauve: '#cba6f7',
            red: '#f38ba8',
            maroon: '#eba0ac',
            peach: '#fab387',
            yellow: '#f9e2af',
            green: '#a6e3a1',
            teal: '#94e2d5',
            sky: '#89dceb',
            sapphire: '#74c7ec',
            blue: '#89b4fa',
            lavender: '#b4befe',
            text: '#cdd6f4',
            subtext1: '#bac2de',
            subtext0: '#a6adc8',
            overlay2: '#9399b2',
            overlay1: '#7f849c',
            overlay0: '#6c7086',
            surface2: '#585b70',
            surface1: '#45475a',
            surface0: '#313244',
            base: '#1e1e2e',
            mantle: '#181825',
            crust: '#11111b'
          },
          monokai: {
            rosewater: '#fcfcfa',
            flamingo: '#fc9867',
            pink: '#ff6188',
            mauve: '#ab9df2',
            red: '#ff6188',
            maroon: '#ff6188',
            peach: '#fc9867',
            yellow: '#ffd866',
            green: '#a9dc76',
            teal: '#a9dc76',
            sky: '#78dce8',
            sapphire: '#78dce8',
            blue: '#78dce8',
            lavender: '#ab9df2',
            text: '#fcfcfa',
            subtext1: '#c1c0c0',
            subtext0: '#ab9df2',
            overlay2: '#939293',
            overlay1: '#727072',
            overlay0: '#5b595c',
            surface2: '#403e41',
            surface1: '#2d2a2e',
            surface0: '#221f22',
            base: '#19181a',
            mantle: '#1e1e20',
            crust: '#161618'
          },
          synthwave: {
            rosewater: '#fdfdfd',
            flamingo: '#fc28a8',
            pink: '#ff7edb',
            mauve: '#ab9df2',
            red: '#fe4450',
            maroon: '#fe4450',
            peach: '#fc9867',
            yellow: '#fede5d',
            green: '#72f1b8',
            teal: '#72f1b8',
            sky: '#36f9f6',
            sapphire: '#36f9f6',
            blue: '#36f9f6',
            lavender: '#ab9df2',
            text: '#fdfdfd',
            subtext1: '#b5afa6',
            subtext0: '#a29a99',
            overlay2: '#8a828c',
            overlay1: '#726b7f',
            overlay0: '#5a5472',
            surface2: '#483d66',
            surface1: '#3e335a',
            surface0: '#34294f',
            base: '#2a2139',
            mantle: '#1e1835',
            crust: '#181430'
          },
          horizon: {
            rosewater: '#ffffff',
            flamingo: '#c2410c',
            pink: '#f472b6',
            mauve: '#7c3aed',
            red: '#e11d48',
            maroon: '#e11d48',
            peach: '#fb923c',
            yellow: '#facc15',
            green: '#16a34a',
            teal: '#14b8a6',
            sky: '#e0f2fe',
            sapphire: '#0ea5e9',
            blue: '#60a5fa',
            lavender: '#7c3aed',
            text: '#020617',
            subtext1: '#1e293b',
            subtext0: '#334155',
            overlay2: '#64748b',
            overlay1: '#94a3b8',
            overlay0: '#cbd5e1',
            surface2: '#e2e8f0',
            surface1: '#dbeafe',
            surface0: '#f1f5f9',
            base: '#ffffff',
            mantle: '#f8fafc',
            crust: '#f1f5f9'
          },
          palenight: {
            rosewater: '#A6ACCD',
            flamingo: '#F07178',
            pink: '#F07178',
            mauve: '#C792EA',
            red: '#E53E3E',
            maroon: '#E53E3E',
            peach: '#F78C6C',
            yellow: '#FFCB6B',
            green: '#C3E88D',
            teal: '#89DDFF',
            sky: '#89DDFF',
            sapphire: '#82AAFF',
            blue: '#82AAFF',
            lavender: '#C792EA',
            text: '#A6ACCD',
            subtext1: '#959CBD',
            subtext0: '#676E95',
            overlay2: '#4E5579',
            overlay1: '#434758',
            overlay0: '#3A3F58',
            surface2: '#3E4554',
            surface1: '#343B51',
            surface0: '#2E3440',
            base: '#292D3E',
            mantle: '#1F2233',
            crust: '#1B1E2B'
          }
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
